#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cd naca0015_sHM
cleanCase
rm -f constant/triSurface/naca0015.stl

cd ../naca0015_2D
cleanCase
rm -rf 0

